// flow-typed signature: df3854189beb5ad9b1d7eb98e6b9c8c5
// flow-typed version: <<STUB>>/app-time_v0.5.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'app-time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'app-time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'app-time/packages/app-scripts/bin/app-time' {
  declare module.exports: any;
}

declare module 'app-time/packages/app-scripts/config/stats' {
  declare module.exports: any;
}

declare module 'app-time/packages/app-scripts/config/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'app-time/packages/app-scripts/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'app-time/packages/app-scripts/scripts/build' {
  declare module.exports: any;
}

declare module 'app-time/packages/app-scripts/scripts/start' {
  declare module.exports: any;
}

declare module 'app-time/packages/app-scripts/utils/babelRequire' {
  declare module.exports: any;
}

declare module 'app-time/packages/app-scripts/utils/clearConsole' {
  declare module.exports: any;
}

declare module 'app-time/packages/app-scripts/utils/paths' {
  declare module.exports: any;
}

// Filename aliases
declare module 'app-time/packages/app-scripts/bin/app-time.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/bin/app-time'>;
}
declare module 'app-time/packages/app-scripts/config/stats.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/config/stats'>;
}
declare module 'app-time/packages/app-scripts/config/webpack.config.dev.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/config/webpack.config.dev'>;
}
declare module 'app-time/packages/app-scripts/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/config/webpack.config.prod'>;
}
declare module 'app-time/packages/app-scripts/scripts/build.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/scripts/build'>;
}
declare module 'app-time/packages/app-scripts/scripts/start.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/scripts/start'>;
}
declare module 'app-time/packages/app-scripts/utils/babelRequire.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/utils/babelRequire'>;
}
declare module 'app-time/packages/app-scripts/utils/clearConsole.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/utils/clearConsole'>;
}
declare module 'app-time/packages/app-scripts/utils/paths.js' {
  declare module.exports: $Exports<'app-time/packages/app-scripts/utils/paths'>;
}
