// flow-typed signature: 3cf8877ee49b97dfcc53d9a16e66a7c1
// flow-typed version: <<STUB>>/eslint-config-zen_v^2.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-zen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-zen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-zen/base' {
  declare module.exports: any;
}

declare module 'eslint-config-zen/flowtype' {
  declare module.exports: any;
}

declare module 'eslint-config-zen/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-zen/base.js' {
  declare module.exports: $Exports<'eslint-config-zen/base'>;
}
declare module 'eslint-config-zen/flowtype.js' {
  declare module.exports: $Exports<'eslint-config-zen/flowtype'>;
}
declare module 'eslint-config-zen/index' {
  declare module.exports: $Exports<'eslint-config-zen'>;
}
declare module 'eslint-config-zen/index.js' {
  declare module.exports: $Exports<'eslint-config-zen'>;
}
declare module 'eslint-config-zen/react.js' {
  declare module.exports: $Exports<'eslint-config-zen/react'>;
}
